package: linkpicker
version: '0.0.3'
author: 'Laurin Waller'

page:
    title: Anker auswählen
    hasLayout: false
    icon: rex-icon fa-crosshairs
    linkAttr: { onclick: 'linkpickerOpenIframe(this, function(string){ copyTextToClipboard(string) }); return false;' }